# -*- coding: utf-8 -*-
"""Unemployment_Analysis_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fapXRF269HSpp-xFfsy9uIRCO1RMPNSx
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Unemployment in India.csv")
df.head()
df.info()
df.describe()

df.isnull().sum()

df.columns

df.columns = ['Region', 'Date', 'Frequency', 'Unemployment Rate (%)', 'Employed', 'Labour Participation Rate (%)', 'State']

df.head()

df.columns = df.columns.str.strip()

plt.figure(figsize=(12, 6))
sns.barplot(x='Unemployment Rate (%)', y='State', data=df.sort_values('Unemployment Rate (%)', ascending=False))
plt.title("Unemployment Rate by State")
plt.show()

# Heatmap by region
region_data = df.groupby('Region').mean(numeric_only=True)
plt.figure(figsize=(10, 6))
sns.heatmap(region_data[['Unemployment Rate (%)']], annot=True, cmap='Reds')
plt.title("Average Unemployment Rate by Region")
plt.show()

"""## *Analysis*

Tripura has the highest unemployment rate-28

Meghalaya has the lowest unemploment rate-4.8
"""

